version: "3.4"

services:
  nodejs:
    image: nodejs_mongo_docker
    build: .
    user: node
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    links:
      - mongodb

  mongodb:
    image: mongo:4.0.24
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
    command: mongod --port 27017 --bind_ip_all

volumes:
  data:
